from __future__ import annotations

from calc_flow import _native as _native
from calc_flow.array import register_jax, register_numpy
from calc_flow.capabilities import (
    OperatorCapability,
    ProviderCapability,
    ProviderOption,
    ProviderOptionsSchema,
    ProviderPort,
    RuntimeCapabilities,
    RuntimeSessionScope,
    UdfCapability,
)
from calc_flow.config import ProjectDocument
from calc_flow.errors import (
    CalcFlowError,
    CancelledError,
    CheckpointError,
    CompileError,
    ConfigError,
    ExecutionError,
    ProviderError,
)
from calc_flow.pipeline import (
    BatchExecutionPlan,
    DeliveryGuarantee,
    ExecutionPlan,
    PipelineBuilder,
    Runtime,
    StreamExecutionPlan,
    StreamRequirements,
    project_json_schema,
    validate_project_json,
)
from calc_flow.runtime import (
    BoundedOutOfOrderness,
    Cursor,
    Data,
    DisabledWatermarks,
    EdgeBudget,
    EpochIdempotentDelivery,
    Idle,
    JobOutcome,
    JobStatus,
    JSONValue,
    LegacyStreamingRunner,
    ManagedCheckpointRuntime,
    MicroBatchRunner,
    NativeWatermarkCapability,
    OrdinaryDelivery,
    ReplayPositioning,
    SinkBinding,
    SinkDelivery,
    SinkRecovery,
    SourceBinding,
    SourceCapabilities,
    SourceDeliveryCapability,
    SourceEvent,
    SourceProvidedWatermarks,
    StreamingError,
    StreamingJob,
    StreamingRunner,
    StreamRuntimeConfig,
    StreamSink,
    StreamSource,
    TransactionalDelivery,
    TransactionalStreamSink,
    Watermark,
    WatermarkPolicy,
)
from calc_flow.store import FileCheckpointStore, FileProjectStore

__version__ = "2.0.0"
Batch = _native.Batch
ExecutionOptions = _native.ExecutionOptions
ProviderContext = _native.ProviderContext
RunResult = _native.RunResult
StreamingRuntimeError = _native.StreamingRuntimeError
CheckpointPublicationUnknownError = _native.CheckpointPublicationUnknownError

__all__ = [
    "Batch",
    "BatchExecutionPlan",
    "BoundedOutOfOrderness",
    "CalcFlowError",
    "CancelledError",
    "CheckpointError",
    "CheckpointPublicationUnknownError",
    "CompileError",
    "ConfigError",
    "Cursor",
    "Data",
    "DisabledWatermarks",
    "EdgeBudget",
    "EpochIdempotentDelivery",
    "ExecutionError",
    "ExecutionOptions",
    "DeliveryGuarantee",
    "FileCheckpointStore",
    "FileProjectStore",
    "Idle",
    "JobOutcome",
    "JobStatus",
    "JSONValue",
    "LegacyStreamingRunner",
    "ManagedCheckpointRuntime",
    "NativeWatermarkCapability",
    "OrdinaryDelivery",
    "ProviderError",
    "ProviderContext",
    "ProjectDocument",
    "ExecutionPlan",
    "PipelineBuilder",
    "OperatorCapability",
    "ProviderCapability",
    "ProviderOption",
    "ProviderOptionsSchema",
    "ProviderPort",
    "MicroBatchRunner",
    "Runtime",
    "RuntimeCapabilities",
    "RuntimeSessionScope",
    "RunResult",
    "ReplayPositioning",
    "SinkBinding",
    "SinkDelivery",
    "SinkRecovery",
    "SourceBinding",
    "SourceCapabilities",
    "SourceDeliveryCapability",
    "SourceEvent",
    "SourceProvidedWatermarks",
    "StreamRuntimeConfig",
    "StreamSink",
    "StreamSource",
    "StreamingError",
    "StreamingJob",
    "StreamingRunner",
    "StreamingRuntimeError",
    "StreamExecutionPlan",
    "StreamRequirements",
    "TransactionalDelivery",
    "TransactionalStreamSink",
    "UdfCapability",
    "register_jax",
    "register_numpy",
    "project_json_schema",
    "validate_project_json",
    "Watermark",
    "WatermarkPolicy",
    "__version__",
]
