from collections.abc import Awaitable, Mapping
from typing import Protocol, TypedDict

import pyarrow as pa

class _ArrowCStream(Protocol):
    def __arrow_c_stream__(
        self, requested_schema: object | None = None, /
    ) -> object: ...

class CalcFlowError(Exception): ...
class ConfigError(CalcFlowError): ...
class CompileError(CalcFlowError): ...
class ExecutionError(CalcFlowError): ...
class ProviderError(ExecutionError): ...
class CheckpointError(CalcFlowError): ...
class CancelledError(ExecutionError): ...

class Batch:
    @staticmethod
    def from_pyarrow(
        table: _ArrowCStream, metadata: Mapping[str, object] | None = None
    ) -> Batch: ...
    @staticmethod
    def _from_external(
        object: object, backend: str, len: int, metadata: Mapping[str, object]
    ) -> Batch:
        """Build an internal Python-provider batch; this is not a stable public API."""
        ...

    def to_pyarrow(self) -> pa.Table: ...
    @property
    def kind(self) -> str: ...
    @property
    def num_rows(self) -> int: ...
    @property
    def metadata(self) -> dict[str, object]: ...

class Runtime:
    def __init__(self) -> None: ...
    def compile_project(self, project_json: str) -> ExecutionPlan: ...

class ExecutionPlan:
    def execute(self, inputs: dict[str, Batch]) -> RunResult: ...
    def execute_async(self, inputs: dict[str, Batch]) -> Awaitable[RunResult]: ...

class _NodeTiming(TypedDict):
    duration_ns: int
    input_rows: dict[str, int]
    output_rows: dict[str, int]

class _DataFusionMetric(TypedDict):
    query_id: int
    node_id: str | None
    planning_ns: int
    execution_ns: int
    output_rows: int
    logical_plan: str
    physical_plan: str

class RunResult:
    @property
    def outputs(self) -> dict[str, Batch]: ...
    @property
    def metadata(self) -> dict[str, str]: ...
    @property
    def node_timings(self) -> dict[str, _NodeTiming]: ...
    @property
    def datafusion_metrics(self) -> list[_DataFusionMetric]: ...

def project_json_schema() -> str: ...
def validate_project_json(project_json: str) -> str: ...
def version() -> str: ...
