// @generated by scripts/generate_rolling_kernel_manifest.py; do not edit.

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum GeneratedTransition {
    Numeric,
    Extrema,
    Pair,
    Ewma,
    FusedDifference,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) enum GeneratedComplexity {
    AmortizedConstant,
    General,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub(super) struct GeneratedKernelCapability {
    pub primitive: &'static str,
    pub batch: bool,
    pub stream: bool,
    pub datafusion: bool,
    pub typed_transition: Option<GeneratedTransition>,
    pub complexity: GeneratedComplexity,
}

pub(super) const GENERATED_KERNEL_CAPABILITIES: &[GeneratedKernelCapability] = &[
    GeneratedKernelCapability {
        primitive: "lag",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: None,
        complexity: GeneratedComplexity::General,
    },
    GeneratedKernelCapability {
        primitive: "delta",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: None,
        complexity: GeneratedComplexity::General,
    },
    GeneratedKernelCapability {
        primitive: "count",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: Some(GeneratedTransition::Numeric),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
    GeneratedKernelCapability {
        primitive: "sum",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: Some(GeneratedTransition::Numeric),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
    GeneratedKernelCapability {
        primitive: "mean",
        batch: true,
        stream: true,
        datafusion: true,
        typed_transition: Some(GeneratedTransition::Numeric),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
    GeneratedKernelCapability {
        primitive: "variance",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: Some(GeneratedTransition::Numeric),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
    GeneratedKernelCapability {
        primitive: "stddev",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: Some(GeneratedTransition::Numeric),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
    GeneratedKernelCapability {
        primitive: "min",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: Some(GeneratedTransition::Extrema),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
    GeneratedKernelCapability {
        primitive: "max",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: Some(GeneratedTransition::Extrema),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
    GeneratedKernelCapability {
        primitive: "covariance",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: Some(GeneratedTransition::Pair),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
    GeneratedKernelCapability {
        primitive: "correlation",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: Some(GeneratedTransition::Pair),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
    GeneratedKernelCapability {
        primitive: "ewma",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: Some(GeneratedTransition::Ewma),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
    GeneratedKernelCapability {
        primitive: "difference",
        batch: true,
        stream: true,
        datafusion: false,
        typed_transition: Some(GeneratedTransition::FusedDifference),
        complexity: GeneratedComplexity::AmortizedConstant,
    },
];

pub(super) fn generated_kernel_capability(
    primitive: &str,
) -> Option<&'static GeneratedKernelCapability> {
    GENERATED_KERNEL_CAPABILITIES
        .iter()
        .find(|capability| capability.primitive == primitive)
}
