# @generated by scripts/generate_rolling_kernel_manifest.py; do not edit.

from __future__ import annotations

from types import MappingProxyType

ROLLING_KERNEL_CAPABILITIES = MappingProxyType(
    {
        "lag": (None, "general", False),
        "delta": (None, "general", False),
        "count": ("numeric", "amortized_constant", False),
        "sum": ("numeric", "amortized_constant", False),
        "mean": ("numeric", "amortized_constant", True),
        "variance": ("numeric", "amortized_constant", False),
        "stddev": ("numeric", "amortized_constant", False),
        "min": ("extrema", "amortized_constant", False),
        "max": ("extrema", "amortized_constant", False),
        "covariance": ("pair", "amortized_constant", False),
        "correlation": ("pair", "amortized_constant", False),
        "ewma": ("ewma", "amortized_constant", False),
        "difference": ("fused_difference", "amortized_constant", False),
    }
)
