/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v3/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_api_v3_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog */
        get: operations["get_catalog_api_v3_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v3_jobs_get"];
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v3_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v3_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v3_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs/{job_id}/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Job Checkpoint */
        post: operations["trigger_job_checkpoint_api_v3_jobs__job_id__checkpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Events */
        get: operations["get_job_events_api_v3_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs/{job_id}/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown Job */
        post: operations["shutdown_job_api_v3_jobs__job_id__shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v3_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v3_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Project */
        post: operations["import_project_api_v3_projects_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v3_projects__project_id__get"];
        /** Put Project */
        put: operations["put_project_api_v3_projects__project_id__put"];
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v3_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Project */
        get: operations["export_project_api_v3_projects__project_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects/{project_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Stored Project */
        post: operations["validate_stored_project_api_v3_projects__project_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/resource-limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resource Limits */
        get: operations["get_resource_limits_api_v3_resource_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/schema/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Schema */
        get: operations["get_project_schema_api_v3_schema_project_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CancelledJobResponse */
        CancelledJobResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: null;
            /** Error Code */
            error_code?: null;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Reason Code */
            reason_code?: null;
            /** Started At */
            started_at?: string | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "cancelled";
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            preview: components["schemas"]["PreviewCapabilitiesResponse"];
            runtime: components["schemas"]["RuntimeCapabilitiesResponse"];
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 2;
        };
        /** CapabilityRuleResponse */
        CapabilityRuleResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** @enum {string} */
        CheckpointSupportValue: "stateless" | "checkpointed_stateful" | "unproven";
        /** CompletedJobResponse */
        CompletedJobResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: null;
            /** Error Code */
            error_code?: null;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Reason Code */
            reason_code?: null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "completed";
        };
        /** ConnectorAxesResponse */
        ConnectorAxesResponse: {
            /** Cdc */
            cdc: boolean;
            /**
             * Delivery
             * @enum {string}
             */
            delivery: "best_effort" | "at_least_once" | "exactly_once";
            /** Lookup */
            lookup: boolean;
            /** Polling */
            polling: boolean;
            /**
             * Replay
             * @enum {string}
             */
            replay: "replayable_exact" | "unreplayable";
            /** Snapshot */
            snapshot: boolean;
            /**
             * Transaction
             * @enum {string}
             */
            transaction: "none" | "pre_commit_commit" | "ledger_idempotent" | "retry_deduplicated";
            /**
             * Watermark
             * @enum {string}
             */
            watermark: "native" | "generated_only";
        };
        /** ConnectorCapabilityResponse */
        ConnectorCapabilityResponse: {
            capabilities: components["schemas"]["ConnectorAxesResponse"];
            /** Formats */
            formats: string[];
            /**
             * Kind
             * @enum {string}
             */
            kind: "source" | "sink" | "both";
            /** Name */
            name: string;
            /** Optionsschema */
            optionsSchema: {
                [key: string]: unknown;
            };
            /** Provider */
            provider: string;
            /** Version */
            version: string;
        };
        /** @enum {string} */
        ExecutionModeValue: "batch" | "stream";
        /** FailedJobResponse */
        FailedJobResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string;
            /**
             * Error Code
             * @enum {string}
             */
            error_code: "job_limit_exceeded" | "worker_failed";
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            reason_code?: components["schemas"]["StreamingFailureReasonCode"] | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "failed";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvalidValidationReport */
        InvalidValidationReport: {
            /** Fingerprint */
            fingerprint?: null;
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "invalid";
            /**
             * Valid
             * @default false
             * @constant
             */
            valid: false;
        };
        "JSONValue-Input": boolean | number | string | components["schemas"]["JSONValue-Input"][] | {
            [key: string]: components["schemas"]["JSONValue-Input"];
        } | null;
        "JSONValue-Output": boolean | number | string | components["schemas"]["JSONValue-Output"][] | {
            [key: string]: components["schemas"]["JSONValue-Output"];
        } | null;
        /** JobCreateRequest */
        JobCreateRequest: {
            /** Project Id */
            project_id: string;
        };
        /**
         * JobResponse
         * @description Typed lifecycle state for one persistent continuous job.
         */
        JobResponse: components["schemas"]["JobResponseVariant"];
        JobResponseVariant: components["schemas"]["PendingJobResponse"] | components["schemas"]["RunningJobResponse"] | components["schemas"]["CompletedJobResponse"] | components["schemas"]["FailedJobResponse"] | components["schemas"]["CancelledJobResponse"];
        /** LazyBuiltinWorkerRegistration */
        LazyBuiltinWorkerRegistration: {
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            reconstruction: "lazyBuiltin";
            /**
             * Registrationkind
             * @enum {string}
             */
            registrationKind: "provider" | "dataFusionScalar";
            /** Version */
            version: string;
        };
        /** OperatorCapabilityResponse */
        OperatorCapabilityResponse: {
            checkpointSupport: components["schemas"]["CheckpointSupportValue"];
            /** Deterministic */
            deterministic: boolean;
            finality: components["schemas"]["OutputFinalityValue"];
            /** Inputports */
            inputPorts: components["schemas"]["ProviderPortResponse"][];
            /** Kind */
            kind: string;
            /** Microbatchinvariant */
            microbatchInvariant: boolean;
            /** Modes */
            modes: components["schemas"]["ExecutionModeValue"][];
            /** Outputports */
            outputPorts: components["schemas"]["ProviderPortResponse"][];
            /** Replaysafe */
            replaySafe: boolean;
            /** Requiresdatafusion */
            requiresDatafusion: boolean;
            /** Requireswatermark */
            requiresWatermark: boolean;
            /** Stateversion */
            stateVersion: number | null;
            /** Stateful */
            stateful: boolean;
            /** Version */
            version: string;
        };
        /** @enum {string} */
        OutputFinalityValue: "per_row_final" | "group_final_append_only" | "unproven";
        /** PendingJobResponse */
        PendingJobResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: null;
            /** Error Code */
            error_code?: null;
            /** Finished At */
            finished_at?: null;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Reason Code */
            reason_code?: null;
            /** Started At */
            started_at?: null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "pending";
        };
        /** PreviewCapabilitiesResponse */
        PreviewCapabilitiesResponse: {
            /** Inputbatchkinds */
            inputBatchKinds: ("table" | "array")[];
            limits: components["schemas"]["PreviewLimitsResponse"];
            /** Projectinputformats */
            projectInputFormats: ("arrow_ipc" | "csv" | "inline_json" | "json")[];
            /** Requestinputformats */
            requestInputFormats: ("arrow_ipc" | "columns" | "records")[];
            /** Workerregistrations */
            workerRegistrations: components["schemas"]["WorkerRegistrationCapability"][];
        };
        /** PreviewLimit */
        PreviewLimit: {
            /** Default */
            default: number;
            /** Maximum */
            maximum: number;
            /** Minimum */
            minimum: number;
        };
        /** PreviewLimitsResponse */
        PreviewLimitsResponse: {
            maxInputBytes: components["schemas"]["PreviewLimit"];
            maxRows: components["schemas"]["PreviewLimit"];
            memoryLimitMb: components["schemas"]["PreviewLimit"];
            outputRows: components["schemas"]["PreviewLimit"];
            timeoutSeconds: components["schemas"]["PreviewLimit"];
        };
        /** Calc Flow Project V3 */
        ProjectCreateRequest: {
            /** @default [] */
            data_sources: components["schemas"]["ProjectCreateRequest"]["$defs"]["DataSourceSpec"][];
            /** @default  */
            description: string;
            /** @constant */
            format_version: 3;
            graph: components["schemas"]["ProjectCreateRequest"]["$defs"]["PipelineSpec"];
            id: string;
            name: string;
            runtime: components["schemas"]["ProjectCreateRequest"]["$defs"]["RuntimeSpec"];
            /** @default [] */
            sinks: components["schemas"]["ProjectCreateRequest"]["$defs"]["ProjectSinkBinding"][];
            /** @default [] */
            sources: components["schemas"]["ProjectCreateRequest"]["$defs"]["ProjectSourceBinding"][];
            /**
             * @default {
             *       "retention": 3,
             *       "root": ".calc-flow-state"
             *     }
             */
            state: components["schemas"]["ProjectCreateRequest"]["$defs"]["StateConfig"];
            $defs: {
                /** @description Aggregate function supported by the first built-in window operator. */
                AggregateFunction: "count" | "sum" | "min" | "max" | "avg";
                /** @description One declared window aggregate and its output column name. */
                AggregateSpec: {
                    /** @description Input column name. */
                    column: string;
                    /** @description Aggregate function. */
                    function: components["schemas"]["ProjectCreateRequest"]["$defs"]["AggregateFunction"];
                    /** @description Output column name. */
                    output: string;
                };
                ArrowFieldSpec: {
                    data_type: string;
                    name: string;
                    /** @default true */
                    nullable: boolean;
                };
                /** @enum {string} */
                BatchKind: "table" | "array";
                /** @description Exact identity of a connector implementation. */
                ConnectorRef: {
                    name: string;
                    provider: string;
                    version: string;
                };
                DataFusionConfig: {
                    /**
                     * Format: uint
                     * @default 8192
                     */
                    batch_size: number;
                    /**
                     * Format: uint
                     * @default 1
                     */
                    target_partitions: number;
                };
                DataSourceSpec: {
                    data: unknown;
                    format: string;
                    id: string;
                    input: string;
                };
                /**
                 * @description Requested delivery guarantee for one project output.
                 * @enum {string}
                 */
                DeliveryRequest: "best_effort" | "at_least_once" | "exactly_once";
                EdgeSpec: {
                    source_node: string;
                    /** @default output */
                    source_port: string;
                    target_node: string;
                    /** @default input */
                    target_port: string;
                };
                /** @description Exact identity of a registered format codec. */
                FormatRef: {
                    name: string;
                    version: string;
                };
                /** @description Hard logical state and per-input fan-out limits. */
                JoinStateLimits: {
                    /** Format: uint64 */
                    max_matches_per_input_batch: number;
                    /** Format: uint64 */
                    max_state_bytes_per_side: number;
                    /** Format: uint64 */
                    max_state_rows_per_side: number;
                };
                /** @description Inclusive event-time distance around one left row. */
                JoinTimeBounds: {
                    /** Format: uint64 */
                    after_micros: number;
                    /** Format: uint64 */
                    before_micros: number;
                };
                /** @description Transaction scope of the `error` late-row policy (API note section 3.2). */
                LateErrorScope: "envelope";
                /** @description Late-row handling for one rolling operator (SCE-00 D7). */
                LatePolicySpec: {
                    /** @constant */
                    kind: "error";
                    /** @description The only supported transaction scope. */
                    scope: components["schemas"]["ProjectCreateRequest"]["$defs"]["LateErrorScope"];
                } | {
                    /** @constant */
                    kind: "drop";
                    /**
                     * Format: uint32
                     * @description Metric transaction version; must equal `1`.
                     */
                    metrics_version: number;
                };
                NodeSpec: {
                    id: string;
                    /** @default [] */
                    input_ports: components["schemas"]["ProjectCreateRequest"]["$defs"]["PortSpec"][];
                    operator: components["schemas"]["ProjectCreateRequest"]["$defs"]["OperatorSpec"];
                    /** @default [] */
                    output_ports: components["schemas"]["ProjectCreateRequest"]["$defs"]["PortSpec"][];
                    position?: components["schemas"]["ProjectCreateRequest"]["$defs"]["PositionSpec"] | null;
                };
                OperatorSpec: {
                    /** @default  */
                    expression: string;
                    filter?: string | null;
                    /** @constant */
                    kind: "expression";
                    /** @default [] */
                    select: string[];
                    /** @default [] */
                    udfs: components["schemas"]["ProjectCreateRequest"]["$defs"]["UdfReference"][];
                } | {
                    aliases: string[];
                    /** @constant */
                    kind: "sql";
                    query: string;
                    /** @default [] */
                    udfs: components["schemas"]["ProjectCreateRequest"]["$defs"]["UdfReference"][];
                } | {
                    /** @constant */
                    kind: "union";
                } | {
                    /** @constant */
                    kind: "window";
                    spec: components["schemas"]["ProjectCreateRequest"]["$defs"]["WindowSpec"];
                } | {
                    /** @constant */
                    kind: "rolling";
                    spec: components["schemas"]["ProjectCreateRequest"]["$defs"]["RollingSpec"];
                } | {
                    /** @constant */
                    kind: "stream_join";
                    spec: components["schemas"]["ProjectCreateRequest"]["$defs"]["StreamJoinSpec"];
                } | {
                    /** @constant */
                    kind: "external";
                    name: string;
                    /** @default {} */
                    options: {
                        [key: string]: unknown;
                    };
                    provider: string;
                    version: string;
                };
                PipelineSpec: {
                    /**
                     * @default {
                     *       "batch_size": 8192,
                     *       "target_partitions": 1
                     *     }
                     */
                    datafusion: components["schemas"]["ProjectCreateRequest"]["$defs"]["DataFusionConfig"];
                    /** @default [] */
                    edges: components["schemas"]["ProjectCreateRequest"]["$defs"]["EdgeSpec"][];
                    name: string;
                    nodes: components["schemas"]["ProjectCreateRequest"]["$defs"]["NodeSpec"][];
                };
                PortSpec: {
                    kind: components["schemas"]["ProjectCreateRequest"]["$defs"]["BatchKind"];
                    name: string;
                    /** @default true */
                    required: boolean;
                    /** @default [] */
                    schema: components["schemas"]["ProjectCreateRequest"]["$defs"]["ArrowFieldSpec"][];
                };
                PositionSpec: {
                    /** Format: double */
                    x: number;
                    /** Format: double */
                    y: number;
                };
                /** @description A data-only sink binding to one registered connector. */
                ProjectSinkBinding: {
                    /** @description External graph output this binding drains. */
                    binding: string;
                    /** @description Exact registered connector identity. */
                    connector: components["schemas"]["ProjectCreateRequest"]["$defs"]["ConnectorRef"];
                    /** @description Requested delivery guarantee for this output. */
                    delivery: components["schemas"]["ProjectCreateRequest"]["$defs"]["DeliveryRequest"];
                    /** @description Optional exact wire-format identity. */
                    format?: components["schemas"]["ProjectCreateRequest"]["$defs"]["FormatRef"] | null;
                    /**
                     * @description Bounded non-secret connector options.
                     * @default {}
                     */
                    options: {
                        [key: string]: unknown;
                    };
                    /**
                     * @description Named secret references resolved only when the connector opens.
                     * @default {}
                     */
                    secrets: {
                        [key: string]: components["schemas"]["ProjectCreateRequest"]["$defs"]["SecretReference"];
                    };
                };
                /** @description A data-only source binding to one registered connector. */
                ProjectSourceBinding: {
                    /** @description External graph input this binding feeds. */
                    binding: string;
                    /** @description Exact registered connector identity. */
                    connector: components["schemas"]["ProjectCreateRequest"]["$defs"]["ConnectorRef"];
                    /** @description Optional exact wire-format identity. */
                    format?: components["schemas"]["ProjectCreateRequest"]["$defs"]["FormatRef"] | null;
                    /**
                     * @description Bounded non-secret connector options.
                     * @default {}
                     */
                    options: {
                        [key: string]: unknown;
                    };
                    /**
                     * @description Optional exact Arrow schema.
                     * @default []
                     */
                    schema: components["schemas"]["ProjectCreateRequest"]["$defs"]["ArrowFieldSpec"][];
                    /**
                     * @description Named secret references resolved only when the connector opens.
                     * @default {}
                     */
                    secrets: {
                        [key: string]: components["schemas"]["ProjectCreateRequest"]["$defs"]["SecretReference"];
                    };
                    /** @description Optional event-time watermark policy. */
                    watermark?: components["schemas"]["ProjectCreateRequest"]["$defs"]["ProjectWatermarkPolicy"] | null;
                };
                /** @description Event-time policy carried by one project source binding. */
                ProjectWatermarkPolicy: {
                    /** @constant */
                    policy: "source_provided";
                } | {
                    column: string;
                    /** Format: uint64 */
                    delay_ms: number;
                    /**
                     * Format: uint64
                     * @default 0
                     */
                    emit_interval_ms: number;
                    /** Format: uint64 */
                    idle_timeout_ms?: number | null;
                    /** @constant */
                    policy: "bounded_out_of_orderness";
                } | {
                    /** @constant */
                    policy: "disabled";
                };
                /**
                 * @description Rolling frame declaration (SCE-00 D5). Only row-count frames are
                 *     supported in this release; duration frames arrive with SCE-08.
                 */
                RollingFrameSpec: {
                    /** @constant */
                    kind: "rows";
                    /**
                     * Format: uint64
                     * @description Positive retained row count.
                     */
                    size: number;
                };
                /** @description One declared rolling output and its output column name. */
                RollingOutputSpec: {
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "lag";
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint64
                     * @description Positive lag distance in rows.
                     */
                    periods: number;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "delta";
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint64
                     * @description Positive lag distance in rows.
                     */
                    periods: number;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /** @description Row-count frame. */
                    frame: components["schemas"]["ProjectCreateRequest"]["$defs"]["RollingFrameSpec"];
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "count";
                    /**
                     * Format: uint64
                     * @description Minimum valid samples for a non-null result.
                     */
                    min_periods: number;
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /** @description Row-count frame. */
                    frame: components["schemas"]["ProjectCreateRequest"]["$defs"]["RollingFrameSpec"];
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "sum";
                    /**
                     * Format: uint64
                     * @description Minimum valid samples for a non-null result.
                     */
                    min_periods: number;
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /** @description Row-count frame. */
                    frame: components["schemas"]["ProjectCreateRequest"]["$defs"]["RollingFrameSpec"];
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "mean";
                    /**
                     * Format: uint64
                     * @description Minimum valid samples for a non-null result.
                     */
                    min_periods: number;
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /**
                     * Format: uint8
                     * @description Degrees-of-freedom adjustment; must be `0` or `1`.
                     */
                    ddof: number;
                    /** @description Row-count frame. */
                    frame: components["schemas"]["ProjectCreateRequest"]["$defs"]["RollingFrameSpec"];
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "variance";
                    /**
                     * Format: uint64
                     * @description Minimum valid samples for a non-null result.
                     */
                    min_periods: number;
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /**
                     * Format: uint8
                     * @description Degrees-of-freedom adjustment; must be `0` or `1`.
                     */
                    ddof: number;
                    /** @description Row-count frame. */
                    frame: components["schemas"]["ProjectCreateRequest"]["$defs"]["RollingFrameSpec"];
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "stddev";
                    /**
                     * Format: uint64
                     * @description Minimum valid samples for a non-null result.
                     */
                    min_periods: number;
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                };
                /** @description Data-only declaration of one native row-window rolling operation. */
                RollingSpec: {
                    /**
                     * Format: uint64
                     * @description Allowed lateness in exact microseconds (SCE-00 D7).
                     */
                    allowed_lateness_micros: number;
                    /**
                     * Format: uint32
                     * @description Semantic configuration version; must equal
                     *     [`ROLLING_CONFIGURATION_VERSION`].
                     */
                    configuration_version: number;
                    /** @description Non-null UTC `timestamp[us]` event-time column. */
                    event_time: string;
                    /** @description Late-row policy. */
                    late_policy: components["schemas"]["ProjectCreateRequest"]["$defs"]["LatePolicySpec"];
                    /** @description Rolling outputs in semantic declaration order. */
                    outputs: components["schemas"]["ProjectCreateRequest"]["$defs"]["RollingOutputSpec"][];
                    /** @description Ordered non-empty entity partition key. */
                    partition_by: string[];
                    /** @description Ordered non-empty sequence key; floating columns are forbidden. */
                    sequence_by: string[];
                    /**
                     * Format: uint32
                     * @description Durable state-layout version; must equal
                     *     [`ROLLING_STATE_LAYOUT_VERSION`].
                     */
                    state_layout_version: number;
                    /** @description Frozen null/NaN value policy. */
                    value_policy: components["schemas"]["ProjectCreateRequest"]["$defs"]["RollingValuePolicy"];
                };
                /** @description Frozen null/NaN policy for rolling values (SCE-00 D3.2). */
                RollingValuePolicy: "stateful_numeric_v1";
                RunOptions: {
                    /**
                     * Format: uint
                     * @default 10485760
                     */
                    max_input_bytes: number;
                    /**
                     * Format: uint
                     * @default 100000
                     */
                    max_rows: number;
                    /**
                     * Format: uint
                     * @default 512
                     */
                    memory_limit_mb: number;
                    /**
                     * Format: uint
                     * @default 1000
                     */
                    output_rows: number;
                    /**
                     * Format: uint64
                     * @default 30
                     */
                    timeout_seconds: number;
                };
                /** @description Runtime mode and mode-specific limits for a project-v3 document. */
                RuntimeSpec: {
                    /** @constant */
                    mode: "batch";
                    options: components["schemas"]["ProjectCreateRequest"]["$defs"]["RunOptions"];
                } | {
                    /** @constant */
                    mode: "stream";
                    options: components["schemas"]["ProjectCreateRequest"]["$defs"]["StreamRunOptions"];
                };
                /**
                 * @description A named pointer to a secret; the only secret-shaped value a data-only
                 *     document may carry.
                 */
                SecretReference: {
                    /** @description Resolver-specific key, for example the variable name. */
                    key: string;
                    /** @description Resolution source. */
                    resolver: components["schemas"]["ProjectCreateRequest"]["$defs"]["SecretResolverKind"];
                };
                /** @description Where a secret reference is resolved from. */
                SecretResolverKind: "environment" | "file" | "registered";
                /** @description Managed state location and checkpoint retention for stream projects. */
                StateConfig: {
                    /**
                     * Format: uint
                     * @default 3
                     */
                    retention: number;
                    /** @default .calc-flow-state */
                    root: string;
                };
                /** @description Immutable declaration for a two-input bounded inner stream Join. */
                StreamJoinSpec: {
                    bounds: components["schemas"]["ProjectCreateRequest"]["$defs"]["JoinTimeBounds"];
                    join_type: components["schemas"]["ProjectCreateRequest"]["$defs"]["StreamJoinType"];
                    left_event_time: string;
                    left_keys: string[];
                    left_prefix: string;
                    limits: components["schemas"]["ProjectCreateRequest"]["$defs"]["JoinStateLimits"];
                    right_event_time: string;
                    right_keys: string[];
                    right_prefix: string;
                };
                /** @description Supported Join semantics. */
                StreamJoinType: "inner";
                /** @description Continuous runtime limits carried by project v3. */
                StreamRunOptions: {
                    /**
                     * Format: uint64
                     * @default 30000
                     */
                    checkpoint_interval_ms: number;
                    /**
                     * Format: uint
                     * @default 67108864
                     */
                    max_batch_bytes: number;
                    /**
                     * Format: uint
                     * @default 10000
                     */
                    max_batch_rows: number;
                };
                /** @enum {string} */
                UdfKind: "data_fusion_scalar" | "external_scalar" | "external_array";
                UdfReference: {
                    kind: components["schemas"]["ProjectCreateRequest"]["$defs"]["UdfKind"];
                    name: string;
                    provider: string;
                    version: string;
                };
                /** @description Fixed UTC window geometry represented in exact microseconds. */
                WindowGeometry: {
                    /** @constant */
                    kind: "tumbling";
                    /**
                     * Format: uint64
                     * @description Window size in exact microseconds.
                     */
                    size_micros: number;
                } | {
                    /** @constant */
                    kind: "hopping";
                    /**
                     * Format: uint64
                     * @description Window size in exact microseconds.
                     */
                    size_micros: number;
                    /**
                     * Format: uint64
                     * @description Window slide in exact microseconds.
                     */
                    slide_micros: number;
                };
                /** @description Data-only declaration of one event-time window aggregation. */
                WindowSpec: {
                    /** @description Aggregates in semantic declaration order. */
                    aggregates: components["schemas"]["ProjectCreateRequest"]["$defs"]["AggregateSpec"][];
                    /** @description Input timestamp column used for window assignment. */
                    event_time_column: string;
                    /** @description Fixed tumbling or hopping geometry. */
                    geometry: components["schemas"]["ProjectCreateRequest"]["$defs"]["WindowGeometry"];
                    /** @description Group columns in semantic declaration order. */
                    group_by: string[];
                };
            };
        };
        /** Calc Flow Project V3 */
        ProjectDocument: {
            /** @default [] */
            data_sources: components["schemas"]["ProjectDocument"]["$defs"]["DataSourceSpec"][];
            /** @default  */
            description: string;
            /** @constant */
            format_version: 3;
            graph: components["schemas"]["ProjectDocument"]["$defs"]["PipelineSpec"];
            id: string;
            name: string;
            runtime: components["schemas"]["ProjectDocument"]["$defs"]["RuntimeSpec"];
            /** @default [] */
            sinks: components["schemas"]["ProjectDocument"]["$defs"]["ProjectSinkBinding"][];
            /** @default [] */
            sources: components["schemas"]["ProjectDocument"]["$defs"]["ProjectSourceBinding"][];
            /**
             * @default {
             *       "retention": 3,
             *       "root": ".calc-flow-state"
             *     }
             */
            state: components["schemas"]["ProjectDocument"]["$defs"]["StateConfig"];
            $defs: {
                /** @description Aggregate function supported by the first built-in window operator. */
                AggregateFunction: "count" | "sum" | "min" | "max" | "avg";
                /** @description One declared window aggregate and its output column name. */
                AggregateSpec: {
                    /** @description Input column name. */
                    column: string;
                    /** @description Aggregate function. */
                    function: components["schemas"]["ProjectDocument"]["$defs"]["AggregateFunction"];
                    /** @description Output column name. */
                    output: string;
                };
                ArrowFieldSpec: {
                    data_type: string;
                    name: string;
                    /** @default true */
                    nullable: boolean;
                };
                /** @enum {string} */
                BatchKind: "table" | "array";
                /** @description Exact identity of a connector implementation. */
                ConnectorRef: {
                    name: string;
                    provider: string;
                    version: string;
                };
                DataFusionConfig: {
                    /**
                     * Format: uint
                     * @default 8192
                     */
                    batch_size: number;
                    /**
                     * Format: uint
                     * @default 1
                     */
                    target_partitions: number;
                };
                DataSourceSpec: {
                    data: unknown;
                    format: string;
                    id: string;
                    input: string;
                };
                /**
                 * @description Requested delivery guarantee for one project output.
                 * @enum {string}
                 */
                DeliveryRequest: "best_effort" | "at_least_once" | "exactly_once";
                EdgeSpec: {
                    source_node: string;
                    /** @default output */
                    source_port: string;
                    target_node: string;
                    /** @default input */
                    target_port: string;
                };
                /** @description Exact identity of a registered format codec. */
                FormatRef: {
                    name: string;
                    version: string;
                };
                /** @description Hard logical state and per-input fan-out limits. */
                JoinStateLimits: {
                    /** Format: uint64 */
                    max_matches_per_input_batch: number;
                    /** Format: uint64 */
                    max_state_bytes_per_side: number;
                    /** Format: uint64 */
                    max_state_rows_per_side: number;
                };
                /** @description Inclusive event-time distance around one left row. */
                JoinTimeBounds: {
                    /** Format: uint64 */
                    after_micros: number;
                    /** Format: uint64 */
                    before_micros: number;
                };
                /** @description Transaction scope of the `error` late-row policy (API note section 3.2). */
                LateErrorScope: "envelope";
                /** @description Late-row handling for one rolling operator (SCE-00 D7). */
                LatePolicySpec: {
                    /** @constant */
                    kind: "error";
                    /** @description The only supported transaction scope. */
                    scope: components["schemas"]["ProjectDocument"]["$defs"]["LateErrorScope"];
                } | {
                    /** @constant */
                    kind: "drop";
                    /**
                     * Format: uint32
                     * @description Metric transaction version; must equal `1`.
                     */
                    metrics_version: number;
                };
                NodeSpec: {
                    id: string;
                    /** @default [] */
                    input_ports: components["schemas"]["ProjectDocument"]["$defs"]["PortSpec"][];
                    operator: components["schemas"]["ProjectDocument"]["$defs"]["OperatorSpec"];
                    /** @default [] */
                    output_ports: components["schemas"]["ProjectDocument"]["$defs"]["PortSpec"][];
                    position?: components["schemas"]["ProjectDocument"]["$defs"]["PositionSpec"] | null;
                };
                OperatorSpec: {
                    /** @default  */
                    expression: string;
                    filter?: string | null;
                    /** @constant */
                    kind: "expression";
                    /** @default [] */
                    select: string[];
                    /** @default [] */
                    udfs: components["schemas"]["ProjectDocument"]["$defs"]["UdfReference"][];
                } | {
                    aliases: string[];
                    /** @constant */
                    kind: "sql";
                    query: string;
                    /** @default [] */
                    udfs: components["schemas"]["ProjectDocument"]["$defs"]["UdfReference"][];
                } | {
                    /** @constant */
                    kind: "union";
                } | {
                    /** @constant */
                    kind: "window";
                    spec: components["schemas"]["ProjectDocument"]["$defs"]["WindowSpec"];
                } | {
                    /** @constant */
                    kind: "rolling";
                    spec: components["schemas"]["ProjectDocument"]["$defs"]["RollingSpec"];
                } | {
                    /** @constant */
                    kind: "stream_join";
                    spec: components["schemas"]["ProjectDocument"]["$defs"]["StreamJoinSpec"];
                } | {
                    /** @constant */
                    kind: "external";
                    name: string;
                    /** @default {} */
                    options: {
                        [key: string]: unknown;
                    };
                    provider: string;
                    version: string;
                };
                PipelineSpec: {
                    /**
                     * @default {
                     *       "batch_size": 8192,
                     *       "target_partitions": 1
                     *     }
                     */
                    datafusion: components["schemas"]["ProjectDocument"]["$defs"]["DataFusionConfig"];
                    /** @default [] */
                    edges: components["schemas"]["ProjectDocument"]["$defs"]["EdgeSpec"][];
                    name: string;
                    nodes: components["schemas"]["ProjectDocument"]["$defs"]["NodeSpec"][];
                };
                PortSpec: {
                    kind: components["schemas"]["ProjectDocument"]["$defs"]["BatchKind"];
                    name: string;
                    /** @default true */
                    required: boolean;
                    /** @default [] */
                    schema: components["schemas"]["ProjectDocument"]["$defs"]["ArrowFieldSpec"][];
                };
                PositionSpec: {
                    /** Format: double */
                    x: number;
                    /** Format: double */
                    y: number;
                };
                /** @description A data-only sink binding to one registered connector. */
                ProjectSinkBinding: {
                    /** @description External graph output this binding drains. */
                    binding: string;
                    /** @description Exact registered connector identity. */
                    connector: components["schemas"]["ProjectDocument"]["$defs"]["ConnectorRef"];
                    /** @description Requested delivery guarantee for this output. */
                    delivery: components["schemas"]["ProjectDocument"]["$defs"]["DeliveryRequest"];
                    /** @description Optional exact wire-format identity. */
                    format?: components["schemas"]["ProjectDocument"]["$defs"]["FormatRef"] | null;
                    /**
                     * @description Bounded non-secret connector options.
                     * @default {}
                     */
                    options: {
                        [key: string]: unknown;
                    };
                    /**
                     * @description Named secret references resolved only when the connector opens.
                     * @default {}
                     */
                    secrets: {
                        [key: string]: components["schemas"]["ProjectDocument"]["$defs"]["SecretReference"];
                    };
                };
                /** @description A data-only source binding to one registered connector. */
                ProjectSourceBinding: {
                    /** @description External graph input this binding feeds. */
                    binding: string;
                    /** @description Exact registered connector identity. */
                    connector: components["schemas"]["ProjectDocument"]["$defs"]["ConnectorRef"];
                    /** @description Optional exact wire-format identity. */
                    format?: components["schemas"]["ProjectDocument"]["$defs"]["FormatRef"] | null;
                    /**
                     * @description Bounded non-secret connector options.
                     * @default {}
                     */
                    options: {
                        [key: string]: unknown;
                    };
                    /**
                     * @description Optional exact Arrow schema.
                     * @default []
                     */
                    schema: components["schemas"]["ProjectDocument"]["$defs"]["ArrowFieldSpec"][];
                    /**
                     * @description Named secret references resolved only when the connector opens.
                     * @default {}
                     */
                    secrets: {
                        [key: string]: components["schemas"]["ProjectDocument"]["$defs"]["SecretReference"];
                    };
                    /** @description Optional event-time watermark policy. */
                    watermark?: components["schemas"]["ProjectDocument"]["$defs"]["ProjectWatermarkPolicy"] | null;
                };
                /** @description Event-time policy carried by one project source binding. */
                ProjectWatermarkPolicy: {
                    /** @constant */
                    policy: "source_provided";
                } | {
                    column: string;
                    /** Format: uint64 */
                    delay_ms: number;
                    /**
                     * Format: uint64
                     * @default 0
                     */
                    emit_interval_ms: number;
                    /** Format: uint64 */
                    idle_timeout_ms?: number | null;
                    /** @constant */
                    policy: "bounded_out_of_orderness";
                } | {
                    /** @constant */
                    policy: "disabled";
                };
                /**
                 * @description Rolling frame declaration (SCE-00 D5). Only row-count frames are
                 *     supported in this release; duration frames arrive with SCE-08.
                 */
                RollingFrameSpec: {
                    /** @constant */
                    kind: "rows";
                    /**
                     * Format: uint64
                     * @description Positive retained row count.
                     */
                    size: number;
                };
                /** @description One declared rolling output and its output column name. */
                RollingOutputSpec: {
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "lag";
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint64
                     * @description Positive lag distance in rows.
                     */
                    periods: number;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "delta";
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint64
                     * @description Positive lag distance in rows.
                     */
                    periods: number;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /** @description Row-count frame. */
                    frame: components["schemas"]["ProjectDocument"]["$defs"]["RollingFrameSpec"];
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "count";
                    /**
                     * Format: uint64
                     * @description Minimum valid samples for a non-null result.
                     */
                    min_periods: number;
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /** @description Row-count frame. */
                    frame: components["schemas"]["ProjectDocument"]["$defs"]["RollingFrameSpec"];
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "sum";
                    /**
                     * Format: uint64
                     * @description Minimum valid samples for a non-null result.
                     */
                    min_periods: number;
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /** @description Row-count frame. */
                    frame: components["schemas"]["ProjectDocument"]["$defs"]["RollingFrameSpec"];
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "mean";
                    /**
                     * Format: uint64
                     * @description Minimum valid samples for a non-null result.
                     */
                    min_periods: number;
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /**
                     * Format: uint8
                     * @description Degrees-of-freedom adjustment; must be `0` or `1`.
                     */
                    ddof: number;
                    /** @description Row-count frame. */
                    frame: components["schemas"]["ProjectDocument"]["$defs"]["RollingFrameSpec"];
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "variance";
                    /**
                     * Format: uint64
                     * @description Minimum valid samples for a non-null result.
                     */
                    min_periods: number;
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                } | {
                    /**
                     * Format: uint8
                     * @description Degrees-of-freedom adjustment; must be `0` or `1`.
                     */
                    ddof: number;
                    /** @description Row-count frame. */
                    frame: components["schemas"]["ProjectDocument"]["$defs"]["RollingFrameSpec"];
                    /** @description Input column name. */
                    input: string;
                    /** @constant */
                    kind: "stddev";
                    /**
                     * Format: uint64
                     * @description Minimum valid samples for a non-null result.
                     */
                    min_periods: number;
                    /** @description Output column name. */
                    output: string;
                    /**
                     * Format: uint32
                     * @description Primitive version; must equal `1`.
                     */
                    primitive_version: number;
                };
                /** @description Data-only declaration of one native row-window rolling operation. */
                RollingSpec: {
                    /**
                     * Format: uint64
                     * @description Allowed lateness in exact microseconds (SCE-00 D7).
                     */
                    allowed_lateness_micros: number;
                    /**
                     * Format: uint32
                     * @description Semantic configuration version; must equal
                     *     [`ROLLING_CONFIGURATION_VERSION`].
                     */
                    configuration_version: number;
                    /** @description Non-null UTC `timestamp[us]` event-time column. */
                    event_time: string;
                    /** @description Late-row policy. */
                    late_policy: components["schemas"]["ProjectDocument"]["$defs"]["LatePolicySpec"];
                    /** @description Rolling outputs in semantic declaration order. */
                    outputs: components["schemas"]["ProjectDocument"]["$defs"]["RollingOutputSpec"][];
                    /** @description Ordered non-empty entity partition key. */
                    partition_by: string[];
                    /** @description Ordered non-empty sequence key; floating columns are forbidden. */
                    sequence_by: string[];
                    /**
                     * Format: uint32
                     * @description Durable state-layout version; must equal
                     *     [`ROLLING_STATE_LAYOUT_VERSION`].
                     */
                    state_layout_version: number;
                    /** @description Frozen null/NaN value policy. */
                    value_policy: components["schemas"]["ProjectDocument"]["$defs"]["RollingValuePolicy"];
                };
                /** @description Frozen null/NaN policy for rolling values (SCE-00 D3.2). */
                RollingValuePolicy: "stateful_numeric_v1";
                RunOptions: {
                    /**
                     * Format: uint
                     * @default 10485760
                     */
                    max_input_bytes: number;
                    /**
                     * Format: uint
                     * @default 100000
                     */
                    max_rows: number;
                    /**
                     * Format: uint
                     * @default 512
                     */
                    memory_limit_mb: number;
                    /**
                     * Format: uint
                     * @default 1000
                     */
                    output_rows: number;
                    /**
                     * Format: uint64
                     * @default 30
                     */
                    timeout_seconds: number;
                };
                /** @description Runtime mode and mode-specific limits for a project-v3 document. */
                RuntimeSpec: {
                    /** @constant */
                    mode: "batch";
                    options: components["schemas"]["ProjectDocument"]["$defs"]["RunOptions"];
                } | {
                    /** @constant */
                    mode: "stream";
                    options: components["schemas"]["ProjectDocument"]["$defs"]["StreamRunOptions"];
                };
                /**
                 * @description A named pointer to a secret; the only secret-shaped value a data-only
                 *     document may carry.
                 */
                SecretReference: {
                    /** @description Resolver-specific key, for example the variable name. */
                    key: string;
                    /** @description Resolution source. */
                    resolver: components["schemas"]["ProjectDocument"]["$defs"]["SecretResolverKind"];
                };
                /** @description Where a secret reference is resolved from. */
                SecretResolverKind: "environment" | "file" | "registered";
                /** @description Managed state location and checkpoint retention for stream projects. */
                StateConfig: {
                    /**
                     * Format: uint
                     * @default 3
                     */
                    retention: number;
                    /** @default .calc-flow-state */
                    root: string;
                };
                /** @description Immutable declaration for a two-input bounded inner stream Join. */
                StreamJoinSpec: {
                    bounds: components["schemas"]["ProjectDocument"]["$defs"]["JoinTimeBounds"];
                    join_type: components["schemas"]["ProjectDocument"]["$defs"]["StreamJoinType"];
                    left_event_time: string;
                    left_keys: string[];
                    left_prefix: string;
                    limits: components["schemas"]["ProjectDocument"]["$defs"]["JoinStateLimits"];
                    right_event_time: string;
                    right_keys: string[];
                    right_prefix: string;
                };
                /** @description Supported Join semantics. */
                StreamJoinType: "inner";
                /** @description Continuous runtime limits carried by project v3. */
                StreamRunOptions: {
                    /**
                     * Format: uint64
                     * @default 30000
                     */
                    checkpoint_interval_ms: number;
                    /**
                     * Format: uint
                     * @default 67108864
                     */
                    max_batch_bytes: number;
                    /**
                     * Format: uint
                     * @default 10000
                     */
                    max_batch_rows: number;
                };
                /** @enum {string} */
                UdfKind: "data_fusion_scalar" | "external_scalar" | "external_array";
                UdfReference: {
                    kind: components["schemas"]["ProjectDocument"]["$defs"]["UdfKind"];
                    name: string;
                    provider: string;
                    version: string;
                };
                /** @description Fixed UTC window geometry represented in exact microseconds. */
                WindowGeometry: {
                    /** @constant */
                    kind: "tumbling";
                    /**
                     * Format: uint64
                     * @description Window size in exact microseconds.
                     */
                    size_micros: number;
                } | {
                    /** @constant */
                    kind: "hopping";
                    /**
                     * Format: uint64
                     * @description Window size in exact microseconds.
                     */
                    size_micros: number;
                    /**
                     * Format: uint64
                     * @description Window slide in exact microseconds.
                     */
                    slide_micros: number;
                };
                /** @description Data-only declaration of one event-time window aggregation. */
                WindowSpec: {
                    /** @description Aggregates in semantic declaration order. */
                    aggregates: components["schemas"]["ProjectDocument"]["$defs"]["AggregateSpec"][];
                    /** @description Input timestamp column used for window assignment. */
                    event_time_column: string;
                    /** @description Fixed tumbling or hopping geometry. */
                    geometry: components["schemas"]["ProjectDocument"]["$defs"]["WindowGeometry"];
                    /** @description Group columns in semantic declaration order. */
                    group_by: string[];
                };
            };
        };
        /**
         * ProjectInvalidResponse
         * @description The 422 body for join validation routes.
         *
         *     The detail is either the structured invalid `ValidationReport` envelope
         *     (malformed stream Join input and semantic project issues) or the standard
         *     request-validation error list.
         */
        ProjectInvalidResponse: {
            /** Detail */
            detail: components["schemas"]["InvalidValidationReport"] | components["schemas"]["RequestError"][];
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Node Count */
            node_count: number;
        };
        /** ProviderArrayRulesResponse */
        ProviderArrayRulesResponse: {
            safeDtypeRule: components["schemas"]["CapabilityRuleResponse"];
            /** Shaperules */
            shapeRules: components["schemas"]["CapabilityRuleResponse"][];
            /** Supporteddtypes */
            supportedDtypes: string[];
        };
        /** ProviderCapabilityResponse */
        ProviderCapabilityResponse: {
            arrayRules: components["schemas"]["ProviderArrayRulesResponse"] | null;
            checkpointSupport: components["schemas"]["CheckpointSupportValue"];
            /** Deterministic */
            deterministic: boolean;
            finality: components["schemas"]["OutputFinalityValue"];
            /** Inputports */
            inputPorts: components["schemas"]["ProviderPortResponse"][];
            /** Microbatchinvariant */
            microbatchInvariant: boolean;
            /** Modes */
            modes: components["schemas"]["ExecutionModeValue"][];
            /** Name */
            name: string;
            optionsSchema: components["schemas"]["ProviderOptionsSchemaResponse"] | null;
            /** Outputports */
            outputPorts: components["schemas"]["ProviderPortResponse"][];
            /**
             * Partitioncontract
             * @enum {string}
             */
            partitionContract: "none" | "row_axis_independent";
            /** Provider */
            provider: string;
            /** Replaysafe */
            replaySafe: boolean;
            /** Requireswatermark */
            requiresWatermark: boolean;
            /** Stateversion */
            stateVersion: number | null;
            /** Stateful */
            stateful: boolean;
            /** Supportsstaticinputs */
            supportsStaticInputs: boolean;
            /** Version */
            version: string;
        };
        /** ProviderOptionResponse */
        ProviderOptionResponse: {
            /** Name */
            name: string;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /**
             * Valuetype
             * @enum {string}
             */
            valueType: "string" | "integer" | "number" | "boolean";
        };
        /** ProviderOptionsSchemaResponse */
        ProviderOptionsSchemaResponse: {
            /**
             * Additionalproperties
             * @default false
             * @constant
             */
            additionalProperties: false;
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["ProviderOptionResponse"][];
        };
        /** ProviderPortResponse */
        ProviderPortResponse: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "table" | "array";
            /** Name */
            name: string;
            /** Required */
            required: boolean;
        };
        /**
         * RequestError
         * @description One request-validation error as FastAPI emits it.
         */
        RequestError: {
            /** Input */
            input?: unknown | null;
            /**
             * Loc
             * @default []
             */
            loc: (string | number)[];
            /** Msg */
            msg: string;
            /** Type */
            type: string;
        };
        /**
         * ResourceLimits
         * @description Hard bounds for long-running continuous jobs.
         */
        ResourceLimits: {
            /**
             * Job Lifecycle
             * @default user_explicit_stop
             * @constant
             */
            job_lifecycle: "user_explicit_stop";
            /**
             * Max Checkpoint Disk Bytes
             * @default 536870912
             */
            max_checkpoint_disk_bytes: number;
            /**
             * Max Concurrent Jobs
             * @default 4
             */
            max_concurrent_jobs: number;
            /**
             * Max Global Resident Memory Bytes
             * @default 4294967296
             */
            max_global_resident_memory_bytes: number;
            /**
             * Max Job Resident Memory Bytes
             * @default 1073741824
             */
            max_job_resident_memory_bytes: number;
        };
        /** RunningJobResponse */
        RunningJobResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: null;
            /** Error Code */
            error_code?: null;
            /** Finished At */
            finished_at?: null;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Reason Code */
            reason_code?: null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "running";
        };
        /** RuntimeCapabilitiesResponse */
        RuntimeCapabilitiesResponse: {
            /** Batchkinds */
            batchKinds: ("table" | "array")[];
            /** Connectors */
            connectors: components["schemas"]["ConnectorCapabilityResponse"][];
            /** Operators */
            operators: components["schemas"]["OperatorCapabilityResponse"][];
            /** Packageversion */
            packageVersion: string;
            /** Portablearrowtypes */
            portableArrowTypes: string[];
            /** Projectformatversions */
            projectFormatVersions: number[];
            /** Providers */
            providers: components["schemas"]["ProviderCapabilityResponse"][];
            scope: components["schemas"]["RuntimeSessionScopeResponse"];
            /** Udfs */
            udfs: components["schemas"]["UdfCapabilityResponse"][];
        };
        /** RuntimeSessionScopeResponse */
        RuntimeSessionScopeResponse: {
            /**
             * Kind
             * @constant
             */
            kind: "runtimeSession";
            /** Revision */
            revision: number;
            /** Sessionid */
            sessionId: string;
        };
        /** SerializedWorkerRegistration */
        SerializedWorkerRegistration: {
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            reconstruction: "serialized";
            /**
             * Registrationkind
             * @enum {string}
             */
            registrationKind: "provider" | "dataFusionScalar";
            /** Version */
            version: string;
        };
        /** @enum {string} */
        StreamingFailureReasonCode: "join_state_limit_exceeded" | "join_match_limit_exceeded" | "join_counter_overflow" | "join_time_conversion_failed";
        /** UdfCapabilityResponse */
        UdfCapabilityResponse: {
            /** Inputtypes */
            inputTypes: string[];
            /**
             * Kind
             * @constant
             */
            kind: "data_fusion_scalar";
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /** Returntype */
            returnType: string;
            /** Version */
            version: string;
            /** Volatility */
            volatility: string;
        };
        /** UnavailableWorkerRegistration */
        UnavailableWorkerRegistration: {
            /** Name */
            name: string;
            /** Provider */
            provider: string;
            /**
             * Reasoncode
             * @constant
             */
            reasonCode: "serializationFailed";
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            reconstruction: "unavailable";
            /**
             * Registrationkind
             * @enum {string}
             */
            registrationKind: "provider" | "dataFusionScalar";
            /** Version */
            version: string;
        };
        /** ValidValidationReport */
        ValidValidationReport: {
            /** Fingerprint */
            fingerprint: string;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["ValidationIssue"][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "valid";
            /**
             * Valid
             * @default true
             * @constant
             */
            valid: true;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Path */
            path: string;
        };
        ValidationReport: components["schemas"]["ValidValidationReport"] | components["schemas"]["InvalidValidationReport"];
        WorkerRegistrationCapability: components["schemas"]["SerializedWorkerRegistration"] | components["schemas"]["LazyBuiltinWorkerRegistration"] | components["schemas"]["UnavailableWorkerRegistration"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_capabilities_api_v3_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    get_catalog_api_v3_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    list_jobs_api_v3_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"][];
                };
            };
        };
    };
    create_job_api_v3_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v3_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v3_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_job_checkpoint_api_v3_jobs__job_id__checkpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_events_api_v3_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: number | null;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shutdown_job_api_v3_jobs__job_id__shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v3_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_api_v3_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Invalid project document or request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInvalidResponse"];
                };
            };
        };
    };
    import_project_api_v3_projects_import_post: {
        parameters: {
            query: {
                format: string;
                replace?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Invalid project document or request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInvalidResponse"];
                };
            };
        };
    };
    get_project_api_v3_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_project_api_v3_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Invalid project document or request */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectInvalidResponse"];
                };
            };
        };
    };
    delete_project_api_v3_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_api_v3_projects__project_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_stored_project_api_v3_projects__project_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resource_limits_api_v3_resource_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceLimits"];
                };
            };
        };
    };
    get_project_schema_api_v3_schema_project_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
