/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v3/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog */
        get: operations["get_catalog_api_v3_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Capabilities */
        get: operations["get_capabilities_api_v3_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/schema/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Schema */
        get: operations["get_project_schema_api_v3_schema_project_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v3_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v3_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Project */
        post: operations["import_project_api_v3_projects_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v3_projects__project_id__get"];
        /** Put Project */
        put: operations["put_project_api_v3_projects__project_id__put"];
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v3_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Project */
        get: operations["export_project_api_v3_projects__project_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects/{project_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Stored Project */
        post: operations["validate_stored_project_api_v3_projects__project_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects/{project_id}/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Checkpoint */
        get: operations["get_project_checkpoint_api_v3_projects__project_id__checkpoint_get"];
        put?: never;
        post?: never;
        /** Delete Project Checkpoint */
        delete: operations["delete_project_checkpoint_api_v3_projects__project_id__checkpoint_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v3_projects__project_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v3_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Cancel Run */
        delete: operations["cancel_run_api_v3_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Events */
        get: operations["get_run_events_api_v3_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs_api_v3_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v3_jobs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs/{run_id}/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Job Checkpoint */
        post: operations["trigger_job_checkpoint_api_v3_jobs__run_id__checkpoint_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs/{run_id}/shutdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Shutdown Job */
        post: operations["shutdown_job_api_v3_jobs__run_id__shutdown_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs/{run_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Job */
        post: operations["cancel_job_api_v3_jobs__run_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/jobs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job Events */
        get: operations["get_job_events_api_v3_jobs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v3/resource-limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Resource Limits */
        get: operations["get_resource_limits_api_v3_resource_limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArrayOutputPreview */
        ArrayOutputPreview: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "array";
            /** Backend */
            backend: string;
            /** Total Rows */
            total_rows: number;
            /** Truncated */
            truncated: boolean;
            data: components["schemas"]["calc_flow_studio__models__JSONValue-Output"];
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["calc_flow_studio__models__JSONValue-Output"];
            };
        };
        /** CancelledRunResponse */
        CancelledRunResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "cancelled";
            /** Started At */
            started_at?: string | null;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Error */
            error?: null;
            /** Result */
            result?: null;
        };
        /** CapabilitiesResponse */
        CapabilitiesResponse: {
            /**
             * Schemaversion
             * @constant
             */
            schemaVersion: 1;
            runtime: components["schemas"]["RuntimeCapabilitiesResponse"];
            preview: components["schemas"]["PreviewCapabilitiesResponse"];
        };
        /** CheckpointSummary */
        CheckpointSummary: {
            /** Pipeline Name */
            pipeline_name: string;
            /** Exists */
            exists: boolean;
            /** Compatible */
            compatible?: boolean | null;
            /** Pipeline Fingerprint */
            pipeline_fingerprint?: string | null;
            /** Sequence */
            sequence?: number | null;
            source_cursor?: components["schemas"]["calc_flow_studio__models__JSONValue-Output"];
            /** Created At */
            created_at?: string | null;
            /**
             * State Nodes
             * @default []
             */
            state_nodes: string[];
        };
        /** CompletedRunResponse */
        CompletedRunResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "completed";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Error */
            error?: null;
            result: components["schemas"]["RunResultPreview"];
        };
        /** DataFusionMetricPreview */
        DataFusionMetricPreview: {
            /** Query Id */
            query_id: number;
            /** Node Id */
            node_id: string | null;
            /** Planning Ns */
            planning_ns: number;
            /** Execution Ns */
            execution_ns: number;
            /** Output Rows */
            output_rows: number;
            /** Logical Plan */
            logical_plan: string;
            /** Physical Plan */
            physical_plan: string;
        };
        /** FailedRunResponse */
        FailedRunResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "failed";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Error */
            error: string;
            /** Result */
            result?: null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InputPayload */
        InputPayload: {
            /**
             * Format
             * @enum {string}
             */
            format: "records" | "columns" | "arrow_ipc";
            data: components["schemas"]["calc_flow_studio__models__JSONValue-Input"];
            /** Source Id */
            source_id?: string | null;
        };
        /** InvalidValidationReport */
        InvalidValidationReport: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "invalid";
            /**
             * Valid
             * @default false
             * @constant
             */
            valid: false;
            /** Issues */
            issues: components["schemas"]["ValidationIssue"][];
            /** Fingerprint */
            fingerprint?: null;
        };
        /** LazyBuiltinWorkerRegistration */
        LazyBuiltinWorkerRegistration: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            reconstruction: "lazyBuiltin";
            /**
             * Registrationkind
             * @enum {string}
             */
            registrationKind: "provider" | "dataFusionScalar";
            /** Provider */
            provider: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** NodeTimingPreview */
        NodeTimingPreview: {
            /** Duration Ns */
            duration_ns: number;
            /** Input Rows */
            input_rows: {
                [key: string]: number;
            };
            /** Output Rows */
            output_rows: {
                [key: string]: number;
            };
        };
        /** OperatorCapabilityResponse */
        OperatorCapabilityResponse: {
            /** Kind */
            kind: string;
            /** Inputkinds */
            inputKinds: ("table" | "array")[];
            /** Outputkinds */
            outputKinds: ("table" | "array")[];
            /** Requiresdatafusion */
            requiresDatafusion: boolean;
        };
        /** OutputFieldPreview */
        OutputFieldPreview: {
            /** Name */
            name: string;
            /** Type */
            type: string;
            /** Nullable */
            nullable: boolean;
        };
        OutputPreview: components["schemas"]["TableOutputPreview"] | components["schemas"]["ArrayOutputPreview"];
        /** PendingRunResponse */
        PendingRunResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "pending";
            /** Started At */
            started_at?: null;
            /** Finished At */
            finished_at?: null;
            /** Error */
            error?: null;
            /** Result */
            result?: null;
        };
        /** PreviewCapabilitiesResponse */
        PreviewCapabilitiesResponse: {
            /** Inputbatchkinds */
            inputBatchKinds: ("table" | "array")[];
            /** Requestinputformats */
            requestInputFormats: ("arrow_ipc" | "columns" | "records")[];
            /** Projectinputformats */
            projectInputFormats: ("arrow_ipc" | "csv" | "inline_json" | "json")[];
            /** Workerregistrations */
            workerRegistrations: components["schemas"]["WorkerRegistrationCapability"][];
            limits: components["schemas"]["PreviewLimitsResponse"];
        };
        /** PreviewLimit */
        PreviewLimit: {
            /** Default */
            default: number;
            /** Minimum */
            minimum: number;
            /** Maximum */
            maximum: number;
        };
        /** PreviewLimitsResponse */
        PreviewLimitsResponse: {
            maxInputBytes: components["schemas"]["PreviewLimit"];
            maxRows: components["schemas"]["PreviewLimit"];
            timeoutSeconds: components["schemas"]["PreviewLimit"];
            memoryLimitMb: components["schemas"]["PreviewLimit"];
            outputRows: components["schemas"]["PreviewLimit"];
        };
        /** Calc Flow Project V2 */
        ProjectCreateRequest: {
            /** @default [] */
            data_sources: components["schemas"]["ProjectCreateRequest"]["$defs"]["DataSourceSpec"][];
            /** @default  */
            description: string;
            /** @constant */
            format_version: 2;
            id: string;
            name: string;
            pipeline: components["schemas"]["ProjectCreateRequest"]["$defs"]["PipelineSpec"];
            /**
             * @default {
             *       "max_input_bytes": 10485760,
             *       "max_rows": 100000,
             *       "memory_limit_mb": 512,
             *       "output_rows": 1000,
             *       "timeout_seconds": 30
             *     }
             */
            run_options: components["schemas"]["ProjectCreateRequest"]["$defs"]["RunOptions"];
            $defs: {
                ArrowFieldSpec: {
                    data_type: string;
                    name: string;
                    /** @default true */
                    nullable: boolean;
                };
                /** @enum {string} */
                BatchKind: "table" | "array";
                DataFusionConfig: {
                    /**
                     * Format: uint
                     * @default 8192
                     */
                    batch_size: number;
                    /**
                     * Format: uint
                     * @default 1
                     */
                    target_partitions: number;
                };
                DataSourceSpec: {
                    data: unknown;
                    format: string;
                    id: string;
                    input: string;
                };
                EdgeSpec: {
                    source_node: string;
                    /** @default output */
                    source_port: string;
                    target_node: string;
                    /** @default input */
                    target_port: string;
                };
                NodeSpec: {
                    id: string;
                    /** @default [] */
                    input_ports: components["schemas"]["ProjectCreateRequest"]["$defs"]["PortSpec"][];
                    operator: components["schemas"]["ProjectCreateRequest"]["$defs"]["OperatorSpec"];
                    /** @default [] */
                    output_ports: components["schemas"]["ProjectCreateRequest"]["$defs"]["PortSpec"][];
                    position?: components["schemas"]["ProjectCreateRequest"]["$defs"]["PositionSpec"] | null;
                };
                OperatorSpec: {
                    /** @default  */
                    expression: string;
                    filter?: string | null;
                    /** @constant */
                    kind: "expression";
                    /** @default [] */
                    select: string[];
                    /** @default [] */
                    udfs: components["schemas"]["ProjectCreateRequest"]["$defs"]["UdfReference"][];
                } | {
                    aliases: string[];
                    /** @constant */
                    kind: "sql";
                    query: string;
                    /** @default [] */
                    udfs: components["schemas"]["ProjectCreateRequest"]["$defs"]["UdfReference"][];
                } | {
                    /** @constant */
                    kind: "external";
                    name: string;
                    /** @default {} */
                    options: {
                        [key: string]: unknown;
                    };
                    provider: string;
                    version: string;
                };
                PipelineSpec: {
                    /**
                     * @default {
                     *       "batch_size": 8192,
                     *       "target_partitions": 1
                     *     }
                     */
                    datafusion: components["schemas"]["ProjectCreateRequest"]["$defs"]["DataFusionConfig"];
                    /** @default [] */
                    edges: components["schemas"]["ProjectCreateRequest"]["$defs"]["EdgeSpec"][];
                    name: string;
                    nodes: components["schemas"]["ProjectCreateRequest"]["$defs"]["NodeSpec"][];
                };
                PortSpec: {
                    kind: components["schemas"]["ProjectCreateRequest"]["$defs"]["BatchKind"];
                    name: string;
                    /** @default true */
                    required: boolean;
                    /** @default [] */
                    schema: components["schemas"]["ProjectCreateRequest"]["$defs"]["ArrowFieldSpec"][];
                };
                PositionSpec: {
                    /** Format: double */
                    x: number;
                    /** Format: double */
                    y: number;
                };
                RunOptions: {
                    /**
                     * Format: uint
                     * @default 10485760
                     */
                    max_input_bytes: number;
                    /**
                     * Format: uint
                     * @default 100000
                     */
                    max_rows: number;
                    /**
                     * Format: uint
                     * @default 512
                     */
                    memory_limit_mb: number;
                    /**
                     * Format: uint
                     * @default 1000
                     */
                    output_rows: number;
                    /**
                     * Format: uint64
                     * @default 30
                     */
                    timeout_seconds: number;
                };
                /** @enum {string} */
                UdfKind: "data_fusion_scalar" | "external_scalar" | "external_array";
                UdfReference: {
                    kind: components["schemas"]["ProjectCreateRequest"]["$defs"]["UdfKind"];
                    name: string;
                    provider: string;
                    version: string;
                };
            };
        };
        /** Calc Flow Project V2 */
        ProjectDocument: {
            /** @default [] */
            data_sources: components["schemas"]["ProjectDocument"]["$defs"]["DataSourceSpec"][];
            /** @default  */
            description: string;
            /** @constant */
            format_version: 2;
            id: string;
            name: string;
            pipeline: components["schemas"]["ProjectDocument"]["$defs"]["PipelineSpec"];
            /**
             * @default {
             *       "max_input_bytes": 10485760,
             *       "max_rows": 100000,
             *       "memory_limit_mb": 512,
             *       "output_rows": 1000,
             *       "timeout_seconds": 30
             *     }
             */
            run_options: components["schemas"]["ProjectDocument"]["$defs"]["RunOptions"];
            $defs: {
                ArrowFieldSpec: {
                    data_type: string;
                    name: string;
                    /** @default true */
                    nullable: boolean;
                };
                /** @enum {string} */
                BatchKind: "table" | "array";
                DataFusionConfig: {
                    /**
                     * Format: uint
                     * @default 8192
                     */
                    batch_size: number;
                    /**
                     * Format: uint
                     * @default 1
                     */
                    target_partitions: number;
                };
                DataSourceSpec: {
                    data: unknown;
                    format: string;
                    id: string;
                    input: string;
                };
                EdgeSpec: {
                    source_node: string;
                    /** @default output */
                    source_port: string;
                    target_node: string;
                    /** @default input */
                    target_port: string;
                };
                NodeSpec: {
                    id: string;
                    /** @default [] */
                    input_ports: components["schemas"]["ProjectDocument"]["$defs"]["PortSpec"][];
                    operator: components["schemas"]["ProjectDocument"]["$defs"]["OperatorSpec"];
                    /** @default [] */
                    output_ports: components["schemas"]["ProjectDocument"]["$defs"]["PortSpec"][];
                    position?: components["schemas"]["ProjectDocument"]["$defs"]["PositionSpec"] | null;
                };
                OperatorSpec: {
                    /** @default  */
                    expression: string;
                    filter?: string | null;
                    /** @constant */
                    kind: "expression";
                    /** @default [] */
                    select: string[];
                    /** @default [] */
                    udfs: components["schemas"]["ProjectDocument"]["$defs"]["UdfReference"][];
                } | {
                    aliases: string[];
                    /** @constant */
                    kind: "sql";
                    query: string;
                    /** @default [] */
                    udfs: components["schemas"]["ProjectDocument"]["$defs"]["UdfReference"][];
                } | {
                    /** @constant */
                    kind: "external";
                    name: string;
                    /** @default {} */
                    options: {
                        [key: string]: unknown;
                    };
                    provider: string;
                    version: string;
                };
                PipelineSpec: {
                    /**
                     * @default {
                     *       "batch_size": 8192,
                     *       "target_partitions": 1
                     *     }
                     */
                    datafusion: components["schemas"]["ProjectDocument"]["$defs"]["DataFusionConfig"];
                    /** @default [] */
                    edges: components["schemas"]["ProjectDocument"]["$defs"]["EdgeSpec"][];
                    name: string;
                    nodes: components["schemas"]["ProjectDocument"]["$defs"]["NodeSpec"][];
                };
                PortSpec: {
                    kind: components["schemas"]["ProjectDocument"]["$defs"]["BatchKind"];
                    name: string;
                    /** @default true */
                    required: boolean;
                    /** @default [] */
                    schema: components["schemas"]["ProjectDocument"]["$defs"]["ArrowFieldSpec"][];
                };
                PositionSpec: {
                    /** Format: double */
                    x: number;
                    /** Format: double */
                    y: number;
                };
                RunOptions: {
                    /**
                     * Format: uint
                     * @default 10485760
                     */
                    max_input_bytes: number;
                    /**
                     * Format: uint
                     * @default 100000
                     */
                    max_rows: number;
                    /**
                     * Format: uint
                     * @default 512
                     */
                    memory_limit_mb: number;
                    /**
                     * Format: uint
                     * @default 1000
                     */
                    output_rows: number;
                    /**
                     * Format: uint64
                     * @default 30
                     */
                    timeout_seconds: number;
                };
                /** @enum {string} */
                UdfKind: "data_fusion_scalar" | "external_scalar" | "external_array";
                UdfReference: {
                    kind: components["schemas"]["ProjectDocument"]["$defs"]["UdfKind"];
                    name: string;
                    provider: string;
                    version: string;
                };
            };
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /** Node Count */
            node_count: number;
        };
        /** ProviderCapabilityResponse */
        ProviderCapabilityResponse: {
            /** Provider */
            provider: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /** Inputports */
            inputPorts: components["schemas"]["ProviderPortResponse"][];
            /** Outputports */
            outputPorts: components["schemas"]["ProviderPortResponse"][];
            optionsSchema: components["schemas"]["ProviderOptionsSchemaResponse"] | null;
        };
        /** ProviderOptionResponse */
        ProviderOptionResponse: {
            /** Name */
            name: string;
            /**
             * Valuetype
             * @enum {string}
             */
            valueType: "string" | "integer" | "number" | "boolean";
            /**
             * Required
             * @default false
             */
            required: boolean;
        };
        /** ProviderOptionsSchemaResponse */
        ProviderOptionsSchemaResponse: {
            /**
             * Fields
             * @default []
             */
            fields: components["schemas"]["ProviderOptionResponse"][];
            /**
             * Additionalproperties
             * @default false
             * @constant
             */
            additionalProperties: false;
        };
        /** ProviderPortResponse */
        ProviderPortResponse: {
            /** Name */
            name: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "table" | "array";
            /** Required */
            required: boolean;
        };
        /**
         * ResourceLimits
         * @description Equivalent resource bounds replacing the v2 worker timeout for
         *     long-running continuous jobs (M6-09).
         */
        ResourceLimits: {
            /**
             * Max Concurrent Jobs
             * @default 4
             */
            max_concurrent_jobs: number;
            /**
             * Max Job Memory Mb
             * @default 1024
             */
            max_job_memory_mb: number;
            /**
             * Max Global Memory Mb
             * @default 4096
             */
            max_global_memory_mb: number;
            /**
             * Max Checkpoint Disk Mb
             * @default 512
             */
            max_checkpoint_disk_mb: number;
            /**
             * Job Lifecycle
             * @default user_explicit_stop
             * @constant
             */
            job_lifecycle: "user_explicit_stop";
        };
        /** RunOptions */
        RunOptions: {
            /**
             * Timeout Seconds
             * @default 30
             */
            timeout_seconds: number;
            /**
             * Memory Limit Mb
             * @default 512
             */
            memory_limit_mb: number;
            /**
             * Max Input Bytes
             * @default 10485760
             */
            max_input_bytes: number;
            /**
             * Max Rows
             * @default 100000
             */
            max_rows: number;
            /**
             * Output Rows
             * @default 1000
             */
            output_rows: number;
        };
        /** RunRequest */
        RunRequest: {
            /** Inputs */
            inputs?: {
                [key: string]: components["schemas"]["InputPayload"];
            };
            options?: components["schemas"]["RunOptions"] | null;
        };
        /** RunResponse */
        RunResponse: components["schemas"]["RunResponseVariant"];
        RunResponseVariant: components["schemas"]["PendingRunResponse"] | components["schemas"]["RunningRunResponse"] | components["schemas"]["CompletedRunResponse"] | components["schemas"]["FailedRunResponse"] | components["schemas"]["TimedOutRunResponse"] | components["schemas"]["CancelledRunResponse"];
        /** RunResultPreview */
        RunResultPreview: {
            /** Outputs */
            outputs: {
                [key: string]: components["schemas"]["OutputPreview"];
            };
            /** Node Timings */
            node_timings: {
                [key: string]: components["schemas"]["NodeTimingPreview"];
            };
            /** Datafusion Metrics */
            datafusion_metrics: components["schemas"]["DataFusionMetricPreview"][];
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["calc_flow_studio__models__JSONValue-Output"];
            };
        };
        /** RunningRunResponse */
        RunningRunResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "running";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Finished At */
            finished_at?: null;
            /** Error */
            error?: null;
            /** Result */
            result?: null;
        };
        /** RuntimeCapabilitiesResponse */
        RuntimeCapabilitiesResponse: {
            scope: components["schemas"]["RuntimeSessionScopeResponse"];
            /** Packageversion */
            packageVersion: string;
            /** Projectformatversions */
            projectFormatVersions: number[];
            /** Batchkinds */
            batchKinds: ("table" | "array")[];
            /** Portablearrowtypes */
            portableArrowTypes: string[];
            /** Operators */
            operators: components["schemas"]["OperatorCapabilityResponse"][];
            /** Udfs */
            udfs: components["schemas"]["UdfCapabilityResponse"][];
            /** Providers */
            providers: components["schemas"]["ProviderCapabilityResponse"][];
        };
        /** RuntimeSessionScopeResponse */
        RuntimeSessionScopeResponse: {
            /**
             * Kind
             * @constant
             */
            kind: "runtimeSession";
            /** Sessionid */
            sessionId: string;
            /** Revision */
            revision: number;
        };
        /** SerializedWorkerRegistration */
        SerializedWorkerRegistration: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            reconstruction: "serialized";
            /**
             * Registrationkind
             * @enum {string}
             */
            registrationKind: "provider" | "dataFusionScalar";
            /** Provider */
            provider: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /** TableOutputPreview */
        TableOutputPreview: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "table";
            /** Total Rows */
            total_rows: number;
            /** Truncated */
            truncated: boolean;
            /** Schema */
            schema: components["schemas"]["OutputFieldPreview"][];
            /** Rows */
            rows: {
                [key: string]: components["schemas"]["calc_flow_studio__models__JSONValue-Output"];
            }[];
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["calc_flow_studio__models__JSONValue-Output"];
            };
        };
        /** TimedOutRunResponse */
        TimedOutRunResponse: {
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "timed_out";
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Finished At
             * Format: date-time
             */
            finished_at: string;
            /** Error */
            error: string;
            /** Result */
            result?: null;
        };
        /** UdfCapabilityResponse */
        UdfCapabilityResponse: {
            /** Provider */
            provider: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Kind
             * @constant
             */
            kind: "data_fusion_scalar";
            /** Inputtypes */
            inputTypes: string[];
            /** Returntype */
            returnType: string;
            /** Volatility */
            volatility: string;
        };
        /** UnavailableWorkerRegistration */
        UnavailableWorkerRegistration: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            reconstruction: "unavailable";
            /**
             * Registrationkind
             * @enum {string}
             */
            registrationKind: "provider" | "dataFusionScalar";
            /** Provider */
            provider: string;
            /** Name */
            name: string;
            /** Version */
            version: string;
            /**
             * Reasoncode
             * @constant
             */
            reasonCode: "serializationFailed";
        };
        /** ValidValidationReport */
        ValidValidationReport: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "valid";
            /**
             * Valid
             * @default true
             * @constant
             */
            valid: true;
            /**
             * Issues
             * @default []
             */
            issues: components["schemas"]["ValidationIssue"][];
            /** Fingerprint */
            fingerprint: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Path */
            path: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        ValidationReport: components["schemas"]["ValidValidationReport"] | components["schemas"]["InvalidValidationReport"];
        WorkerRegistrationCapability: components["schemas"]["SerializedWorkerRegistration"] | components["schemas"]["LazyBuiltinWorkerRegistration"] | components["schemas"]["UnavailableWorkerRegistration"];
        "calc_flow__config__JSONValue-Input": boolean | number | string | components["schemas"]["calc_flow__config__JSONValue-Input"][] | {
            [key: string]: components["schemas"]["calc_flow__config__JSONValue-Input"];
        } | null;
        "calc_flow__config__JSONValue-Output": boolean | number | string | components["schemas"]["calc_flow__config__JSONValue-Output"][] | {
            [key: string]: components["schemas"]["calc_flow__config__JSONValue-Output"];
        } | null;
        "calc_flow_studio__models__JSONValue-Input": boolean | number | string | components["schemas"]["calc_flow_studio__models__JSONValue-Input"][] | {
            [key: string]: components["schemas"]["calc_flow_studio__models__JSONValue-Input"];
        } | null;
        "calc_flow_studio__models__JSONValue-Output": boolean | number | string | components["schemas"]["calc_flow_studio__models__JSONValue-Output"][] | {
            [key: string]: components["schemas"]["calc_flow_studio__models__JSONValue-Output"];
        } | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_catalog_api_v3_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    get_capabilities_api_v3_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CapabilitiesResponse"];
                };
            };
        };
    };
    get_project_schema_api_v3_schema_project_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_projects_api_v3_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_api_v3_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_project_api_v3_projects_import_post: {
        parameters: {
            query: {
                format: string;
                replace?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v3_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_project_api_v3_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v3_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_api_v3_projects__project_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_stored_project_api_v3_projects__project_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_checkpoint_api_v3_projects__project_id__checkpoint_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_checkpoint_api_v3_projects__project_id__checkpoint_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v3_projects__project_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v3_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v3_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_api_v3_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: number | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_api_v3_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"][];
                };
            };
        };
    };
    get_job_api_v3_jobs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_job_checkpoint_api_v3_jobs__run_id__checkpoint_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    shutdown_job_api_v3_jobs__run_id__shutdown_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_api_v3_jobs__run_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_events_api_v3_jobs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: number | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_resource_limits_api_v3_resource_limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResourceLimits"];
                };
            };
        };
    };
}
