/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v2/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog */
        get: operations["get_catalog_api_v2_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v2_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v2_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Project */
        post: operations["import_project_api_v2_projects_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v2_projects__project_id__get"];
        /** Put Project */
        put: operations["put_project_api_v2_projects__project_id__put"];
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_v2_projects__project_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects/{project_id}/checkpoint": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Checkpoint */
        get: operations["get_project_checkpoint_api_v2_projects__project_id__checkpoint_get"];
        put?: never;
        post?: never;
        /** Delete Project Checkpoint */
        delete: operations["delete_project_checkpoint_api_v2_projects__project_id__checkpoint_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Project */
        get: operations["export_project_api_v2_projects__project_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects/{project_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Run */
        post: operations["create_run_api_v2_projects__project_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/projects/{project_id}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Stored Project */
        post: operations["validate_stored_project_api_v2_projects__project_id__validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_v2_runs__run_id__get"];
        put?: never;
        post?: never;
        /** Cancel Run */
        delete: operations["cancel_run_api_v2_runs__run_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run Events */
        get: operations["get_run_events_api_v2_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v2/schema/project": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Schema */
        get: operations["get_project_schema_api_v2_schema_project_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CheckpointSummary */
        CheckpointSummary: {
            /** Compatible */
            compatible?: boolean | null;
            /** Created At */
            created_at?: string | null;
            /** Exists */
            exists: boolean;
            /** Pipeline Fingerprint */
            pipeline_fingerprint?: string | null;
            /** Pipeline Name */
            pipeline_name: string;
            /** Sequence */
            sequence?: number | null;
            source_cursor?: components["schemas"]["calc_flow_studio__models__JSONValue-Output"];
            /**
             * State Nodes
             * @default []
             */
            state_nodes: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InputPayload */
        InputPayload: {
            data: components["schemas"]["calc_flow_studio__models__JSONValue-Input"];
            /**
             * Format
             * @enum {string}
             */
            format: "records" | "columns" | "arrow_ipc";
            /** Source Id */
            source_id?: string | null;
        };
        /** Calc Flow Project V2 */
        ProjectCreateRequest: {
            /** @default [] */
            data_sources: components["schemas"]["ProjectCreateRequest"]["$defs"]["DataSourceSpec"][];
            /** @default  */
            description: string;
            /** @constant */
            format_version: 2;
            id: string;
            name: string;
            pipeline: components["schemas"]["ProjectCreateRequest"]["$defs"]["PipelineSpec"];
            /**
             * @default {
             *       "max_input_bytes": 10485760,
             *       "max_rows": 100000,
             *       "memory_limit_mb": 512,
             *       "output_rows": 1000,
             *       "timeout_seconds": 30
             *     }
             */
            run_options: components["schemas"]["ProjectCreateRequest"]["$defs"]["RunOptions"];
            $defs: {
                ArrowFieldSpec: {
                    data_type: string;
                    name: string;
                    /** @default true */
                    nullable: boolean;
                };
                /** @enum {string} */
                BatchKind: "table" | "array";
                DataFusionConfig: {
                    /**
                     * Format: uint
                     * @default 8192
                     */
                    batch_size: number;
                    /**
                     * Format: uint
                     * @default 1
                     */
                    target_partitions: number;
                };
                DataSourceSpec: {
                    data: unknown;
                    format: string;
                    id: string;
                    input: string;
                };
                EdgeSpec: {
                    source_node: string;
                    /** @default output */
                    source_port: string;
                    target_node: string;
                    /** @default input */
                    target_port: string;
                };
                NodeSpec: {
                    id: string;
                    /** @default [] */
                    input_ports: components["schemas"]["ProjectCreateRequest"]["$defs"]["PortSpec"][];
                    operator: components["schemas"]["ProjectCreateRequest"]["$defs"]["OperatorSpec"];
                    /** @default [] */
                    output_ports: components["schemas"]["ProjectCreateRequest"]["$defs"]["PortSpec"][];
                    position?: components["schemas"]["ProjectCreateRequest"]["$defs"]["PositionSpec"] | null;
                };
                OperatorSpec: {
                    /** @default  */
                    expression: string;
                    filter?: string | null;
                    /** @constant */
                    kind: "expression";
                    /** @default [] */
                    select: string[];
                    /** @default [] */
                    udfs: components["schemas"]["ProjectCreateRequest"]["$defs"]["UdfReference"][];
                } | {
                    aliases: string[];
                    /** @constant */
                    kind: "sql";
                    query: string;
                    /** @default [] */
                    udfs: components["schemas"]["ProjectCreateRequest"]["$defs"]["UdfReference"][];
                } | {
                    /** @constant */
                    kind: "external";
                    name: string;
                    /** @default {} */
                    options: {
                        [key: string]: unknown;
                    };
                    provider: string;
                    version: string;
                };
                PipelineSpec: {
                    /**
                     * @default {
                     *       "batch_size": 8192,
                     *       "target_partitions": 1
                     *     }
                     */
                    datafusion: components["schemas"]["ProjectCreateRequest"]["$defs"]["DataFusionConfig"];
                    /** @default [] */
                    edges: components["schemas"]["ProjectCreateRequest"]["$defs"]["EdgeSpec"][];
                    name: string;
                    nodes: components["schemas"]["ProjectCreateRequest"]["$defs"]["NodeSpec"][];
                };
                PortSpec: {
                    kind: components["schemas"]["ProjectCreateRequest"]["$defs"]["BatchKind"];
                    name: string;
                    /** @default true */
                    required: boolean;
                    /** @default [] */
                    schema: components["schemas"]["ProjectCreateRequest"]["$defs"]["ArrowFieldSpec"][];
                };
                PositionSpec: {
                    /** Format: double */
                    x: number;
                    /** Format: double */
                    y: number;
                };
                RunOptions: {
                    /**
                     * Format: uint
                     * @default 10485760
                     */
                    max_input_bytes: number;
                    /**
                     * Format: uint
                     * @default 100000
                     */
                    max_rows: number;
                    /**
                     * Format: uint
                     * @default 512
                     */
                    memory_limit_mb: number;
                    /**
                     * Format: uint
                     * @default 1000
                     */
                    output_rows: number;
                    /**
                     * Format: uint64
                     * @default 30
                     */
                    timeout_seconds: number;
                };
                /** @enum {string} */
                UdfKind: "data_fusion_scalar" | "external_scalar" | "external_array";
                UdfReference: {
                    kind: components["schemas"]["ProjectCreateRequest"]["$defs"]["UdfKind"];
                    name: string;
                    provider: string;
                    version: string;
                };
            };
        };
        /** Calc Flow Project V2 */
        ProjectDocument: {
            /** @default [] */
            data_sources: components["schemas"]["ProjectDocument"]["$defs"]["DataSourceSpec"][];
            /** @default  */
            description: string;
            /** @constant */
            format_version: 2;
            id: string;
            name: string;
            pipeline: components["schemas"]["ProjectDocument"]["$defs"]["PipelineSpec"];
            /**
             * @default {
             *       "max_input_bytes": 10485760,
             *       "max_rows": 100000,
             *       "memory_limit_mb": 512,
             *       "output_rows": 1000,
             *       "timeout_seconds": 30
             *     }
             */
            run_options: components["schemas"]["ProjectDocument"]["$defs"]["RunOptions"];
            $defs: {
                ArrowFieldSpec: {
                    data_type: string;
                    name: string;
                    /** @default true */
                    nullable: boolean;
                };
                /** @enum {string} */
                BatchKind: "table" | "array";
                DataFusionConfig: {
                    /**
                     * Format: uint
                     * @default 8192
                     */
                    batch_size: number;
                    /**
                     * Format: uint
                     * @default 1
                     */
                    target_partitions: number;
                };
                DataSourceSpec: {
                    data: unknown;
                    format: string;
                    id: string;
                    input: string;
                };
                EdgeSpec: {
                    source_node: string;
                    /** @default output */
                    source_port: string;
                    target_node: string;
                    /** @default input */
                    target_port: string;
                };
                NodeSpec: {
                    id: string;
                    /** @default [] */
                    input_ports: components["schemas"]["ProjectDocument"]["$defs"]["PortSpec"][];
                    operator: components["schemas"]["ProjectDocument"]["$defs"]["OperatorSpec"];
                    /** @default [] */
                    output_ports: components["schemas"]["ProjectDocument"]["$defs"]["PortSpec"][];
                    position?: components["schemas"]["ProjectDocument"]["$defs"]["PositionSpec"] | null;
                };
                OperatorSpec: {
                    /** @default  */
                    expression: string;
                    filter?: string | null;
                    /** @constant */
                    kind: "expression";
                    /** @default [] */
                    select: string[];
                    /** @default [] */
                    udfs: components["schemas"]["ProjectDocument"]["$defs"]["UdfReference"][];
                } | {
                    aliases: string[];
                    /** @constant */
                    kind: "sql";
                    query: string;
                    /** @default [] */
                    udfs: components["schemas"]["ProjectDocument"]["$defs"]["UdfReference"][];
                } | {
                    /** @constant */
                    kind: "external";
                    name: string;
                    /** @default {} */
                    options: {
                        [key: string]: unknown;
                    };
                    provider: string;
                    version: string;
                };
                PipelineSpec: {
                    /**
                     * @default {
                     *       "batch_size": 8192,
                     *       "target_partitions": 1
                     *     }
                     */
                    datafusion: components["schemas"]["ProjectDocument"]["$defs"]["DataFusionConfig"];
                    /** @default [] */
                    edges: components["schemas"]["ProjectDocument"]["$defs"]["EdgeSpec"][];
                    name: string;
                    nodes: components["schemas"]["ProjectDocument"]["$defs"]["NodeSpec"][];
                };
                PortSpec: {
                    kind: components["schemas"]["ProjectDocument"]["$defs"]["BatchKind"];
                    name: string;
                    /** @default true */
                    required: boolean;
                    /** @default [] */
                    schema: components["schemas"]["ProjectDocument"]["$defs"]["ArrowFieldSpec"][];
                };
                PositionSpec: {
                    /** Format: double */
                    x: number;
                    /** Format: double */
                    y: number;
                };
                RunOptions: {
                    /**
                     * Format: uint
                     * @default 10485760
                     */
                    max_input_bytes: number;
                    /**
                     * Format: uint
                     * @default 100000
                     */
                    max_rows: number;
                    /**
                     * Format: uint
                     * @default 512
                     */
                    memory_limit_mb: number;
                    /**
                     * Format: uint
                     * @default 1000
                     */
                    output_rows: number;
                    /**
                     * Format: uint64
                     * @default 30
                     */
                    timeout_seconds: number;
                };
                /** @enum {string} */
                UdfKind: "data_fusion_scalar" | "external_scalar" | "external_array";
                UdfReference: {
                    kind: components["schemas"]["ProjectDocument"]["$defs"]["UdfKind"];
                    name: string;
                    provider: string;
                    version: string;
                };
            };
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Description */
            description: string;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Node Count */
            node_count: number;
        };
        /** RunOptions */
        RunOptions: {
            /**
             * Max Input Bytes
             * @default 10485760
             */
            max_input_bytes: number;
            /**
             * Max Rows
             * @default 100000
             */
            max_rows: number;
            /**
             * Memory Limit Mb
             * @default 512
             */
            memory_limit_mb: number;
            /**
             * Output Rows
             * @default 1000
             */
            output_rows: number;
            /**
             * Timeout Seconds
             * @default 30
             */
            timeout_seconds: number;
        };
        /** RunRequest */
        RunRequest: {
            /** Inputs */
            inputs?: {
                [key: string]: components["schemas"]["InputPayload"];
            };
            options?: components["schemas"]["RunOptions"] | null;
        };
        /** RunResponse */
        RunResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /** Id */
            id: string;
            /** Project Id */
            project_id: string;
            /** Result */
            result?: {
                [key: string]: components["schemas"]["calc_flow_studio__models__JSONValue-Output"];
            } | null;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["RunStatus"];
        };
        /**
         * RunStatus
         * @enum {string}
         */
        RunStatus: "pending" | "running" | "completed" | "failed" | "cancelled" | "timed_out";
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        "calc_flow__config__JSONValue-Input": boolean | number | string | components["schemas"]["calc_flow__config__JSONValue-Input"][] | {
            [key: string]: components["schemas"]["calc_flow__config__JSONValue-Input"];
        } | null;
        "calc_flow__config__JSONValue-Output": boolean | number | string | components["schemas"]["calc_flow__config__JSONValue-Output"][] | {
            [key: string]: components["schemas"]["calc_flow__config__JSONValue-Output"];
        } | null;
        "calc_flow_studio__models__JSONValue-Input": boolean | number | string | components["schemas"]["calc_flow_studio__models__JSONValue-Input"][] | {
            [key: string]: components["schemas"]["calc_flow_studio__models__JSONValue-Input"];
        } | null;
        "calc_flow_studio__models__JSONValue-Output": boolean | number | string | components["schemas"]["calc_flow_studio__models__JSONValue-Output"][] | {
            [key: string]: components["schemas"]["calc_flow_studio__models__JSONValue-Output"];
        } | null;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_catalog_api_v2_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    }[];
                };
            };
        };
    };
    list_projects_api_v2_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
        };
    };
    create_project_api_v2_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_project_api_v2_projects_import_post: {
        parameters: {
            query: {
                format: string;
                replace?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v2_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_project_api_v2_projects__project_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_v2_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_checkpoint_api_v2_projects__project_id__checkpoint_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_checkpoint_api_v2_projects__project_id__checkpoint_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CheckpointSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_api_v2_projects__project_id__export_get: {
        parameters: {
            query?: {
                format?: string;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v2_projects__project_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_stored_project_api_v2_projects__project_id__validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v2_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_run_api_v2_runs__run_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_events_api_v2_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: number | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_schema_api_v2_schema_project_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
